name: publish-releases

on:
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download latest CLI artifact from build workflow
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          workflow_conclusion: completed
          name: crixlyctl-cli-tgz
          path: install
          branch: main
          if_no_artifact_found: warn

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: crixly-install
          directory: install
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
